version: '3.7'

services:
  mongo:
    image: mongo:5.0.28
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: chat
      MONGO_INITDB_ROOT_PASSWORD: chat
    volumes:
      - chat-mongo:/data/db
  chat:
    #build: .
    image: ghcr.io/raaymax/quack:build-32
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      APP_VERSION: 3.x.x
      DATABASE_URL: mongodb://chat:chat@mongo:27017/chat?authSource=admin
      PORT: 8080
    depends_on:
    - mongo

volumes:
  chat-db:
  chat-mongo:
