import type { CapacitorConfig } from "@capacitor/cli";
import * as fs from "node:fs";
import * as path from "node:path";

// Try to load config from mobile.config.json (generated by: npm run config)
// Falls back to QUACK_SERVER_URL env var or example URL
function getServerUrl(): string {
  const configPath = path.join(__dirname, "mobile.config.json");

  if (fs.existsSync(configPath)) {
    try {
      const config = JSON.parse(fs.readFileSync(configPath, "utf-8"));
      if (config.serverUrl) {
        return config.serverUrl;
      }
    } catch (e) {
      console.warn("Failed to read mobile.config.json:", e);
    }
  }

  return process.env.QUACK_SERVER_URL || "https://quack.example.com";
}

// Note: URL normalization for Android emulator (localhost -> 10.0.2.2)
// is handled in QuackConnection.kt to keep config clean and avoid confusion
const serverUrl = getServerUrl();
const isLocalDev = serverUrl.startsWith("http://");

const config: CapacitorConfig = {
  appId: "io.codecat.quack",
  appName: "Quack",
  webDir: "www",

  server: {
    url: serverUrl,
    cleartext: isLocalDev, // Allow HTTP for local development
  },

  android: {
    allowMixedContent: false,
    captureInput: true,
    webContentsDebuggingEnabled: process.env.NODE_ENV !== "production",
  },

  plugins: {},
};

export default config;
